// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjsbknrcfxgpsfsrqbcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqc2JrbnJjZnhncHNmc3JxYmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMTkyNjgsImV4cCI6MjA1NDU5NTI2OH0.OIhL8vK91uRzx4nyfAXxNPE1OAdimzgf62rUltL-72U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);